<a href="https://colab.research.google.com/github/GreatLearningAIML1/gurgaon-feb-batch-abhishek02git/blob/master/SeqNLP_Project1_Answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sentiment Classification


In [0]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive


## Loading the dataset

In [0]:
from keras.datasets import imdb

vocab_size = 10000 #vocab size

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size) # vocab_size is no.of words to consider from the dataset, ordering based on frequency.

In [0]:
x_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [0]:
from keras.preprocessing.sequence import pad_sequences
vocab_size = 10000 #vocab size
maxlen = 300  #number of word used from each review

## Train test split

In [0]:
#load dataset as a list of ints
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)
#make all sequences of the same length
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test =  pad_sequences(x_test, maxlen=maxlen)

In [0]:
x_test

array([[   0,    0,    0, ...,   14,    6,  717],
       [   0,    0,    0, ...,  125,    4, 3077],
       [1239, 5189,  137, ...,    9,   57,  975],
       ...,
       [   0,    0,    0, ...,   21,  846, 5518],
       [   0,    0,    0, ..., 2302,    7,  470],
       [   0,    0,    0, ...,   34, 2005, 2643]], dtype=int32)

In [0]:
# Creating the key value pair with index and value
word_index = imdb.get_word_index()                                    
reverse_word_index = dict([(value,key) for (key,value) in sorted(word_index.items())])

In [0]:
reverse_word_index

{68893: '\x08\x08\x08\x08a',
 70879: '\x10own',
 755: "'",
 17448: "''",
 57351: "''a",
 64015: "''after",
 72030: "''bad",
 58448: "''cannibal",
 80824: "''clients''",
 66872: "''dark''",
 52876: "''empire",
 85943: "''family",
 58747: "''gaslight''",
 75354: "''heart''",
 66908: "''high",
 83565: "''holy",
 61364: "''human''",
 88090: "''humans''",
 61351: "''i'm",
 62727: "''if",
 61770: "''inuyasha''",
 58164: "''little''",
 85895: "''maison",
 62202: "''ned''",
 76149: "''negative''",
 57008: "''nice",
 45418: "''oh",
 66910: "''on",
 75509: "''oversexed''",
 81867: "''peeping",
 76109: "''professionals''",
 44903: "''ranma",
 70722: "''raptors''",
 55138: "''return",
 51394: "''saint",
 51257: "''scarface''",
 49404: "''sea",
 84926: "''talent",
 81627: "''terrorists''",
 20197: "''the",
 84051: "''their",
 66430: "''this",
 87604: "''thunderball",
 79833: "''troubled''",
 66417: "''unpleasant",
 71277: "''villain",
 70370: "''voyeur''",
 66244: "''we're",
 65559: "''while''",
 6

## Build Keras Embedding Layer Model
We can think of the Embedding layer as a dicionary that maps a index assigned to a word to a word vector. This layer is very flexible and can be used in a few ways:

* The embedding layer can be used at the start of a larger deep learning model. 
* Also we could load pre-train word embeddings into the embedding layer when we create our model.
* Use the embedding layer to train our own word2vec models.

The keras embedding layer doesn't require us to onehot encode our words, instead we have to give each word a unqiue intger number as an id. For the imdb dataset we've loaded this has already been done, but if this wasn't the case we could use sklearn [LabelEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html).

In [0]:
import keras
import tensorflow as tf
from keras.layers import LSTM,Dense,Embedding
from keras.models import Sequential
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.preprocessing.text import Tokenizer

In [0]:
# Creating model on our own Embeddings. 
model = Sequential()
model.add(Embedding(vocab_size+1,
                    50,
                    input_length = maxlen))
model.add(LSTM(256, dropout = 0.2, recurrent_dropout= 0.2))
model.add(Dense(1, activation= 'sigmoid'))

In [0]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [0]:
# filepath="/gdrive/My Drive/NLP/Sequence Modelling/Weights/weights.best.hdf5"
# checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
# ES = EarlyStopping(monitor='val_acc', min_delta=0, patience=0, mode='auto', baseline=None, restore_best_weights=False)
# callbacks_list = [ES]

In [0]:
model.fit(x_train,y_train,
          epochs=10,
          batch_size=128,          
          validation_data=(x_test, y_test),
         verbose=1)

Train on 25000 samples, validate on 25000 samples
Epoch 1/10
25000/25000 [==============================] - 127s 5ms/step - loss: 0.1654 - acc: 0.9380 - val_loss: 0.4560 - val_acc: 0.8214
Epoch 2/10
25000/25000 [==============================] - 126s 5ms/step - loss: 0.1442 - acc: 0.9489 - val_loss: 0.4211 - val_acc: 0.8408
Epoch 3/10
25000/25000 [==============================] - 126s 5ms/step - loss: 0.1238 - acc: 0.9557 - val_loss: 0.4937 - val_acc: 0.8476
Epoch 4/10
25000/25000 [==============================] - 126s 5ms/step - loss: 0.0993 - acc: 0.9654 - val_loss: 0.5432 - val_acc: 0.8410
Epoch 5/10
25000/25000 [==============================] - 127s 5ms/step - loss: 0.0903 - acc: 0.9688 - val_loss: 0.5693 - val_acc: 0.8349
Epoch 6/10
25000/25000 [==============================] - 126s 5ms/step - loss: 0.0789 - acc: 0.9738 - val_loss: 0.6118 - val_acc: 0.8355
Epoch 7/10
25000/25000 [==============================] - 126s 5ms/step - loss: 0.0735 - acc: 0.9748 - val_loss: 0.6994 - 

In [0]:
print (model.evaluate(x_train,y_train))
print (model.evaluate(x_test,y_test))

25000/25000 [==============================] - 131s 5ms/step
[0.02132713037803769, 0.99516]
25000/25000 [==============================] - 131s 5ms/step
[0.7270638479340077, 0.84032]


In [0]:
# Accuracy on Test set is 84% while Trainin is 99%.

In [0]:
# Generating Embeddings from the Word2Vec Model

In [0]:
import gensim
import numpy as np
word2vec = gensim.models.Word2Vec.load('/gdrive/My Drive/NLP/Sequence Modelling/Weights/word2vec-movie-50') # Using pre trained model on reviews dataset.

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:402: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [0]:
vocab_size = 10000 #vocab size
maxlen = 300 

In [0]:
# Creating the embedding matrix on the pre trained model.

print (word2vec.wv.syn0.shape)
embedding_vector_length = word2vec.wv.syn0.shape[1]
print (embedding_vector_length)
embedding_matrix = np.zeros((vocab_size + 1, embedding_vector_length))

(28322, 50)
50


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  


In [0]:
embedding_matrix.shape

(10001, 50)

In [0]:
word_index = imdb.get_word_index() # getting the imdb word index and then sorting the numbers from the above trained model.

for word, i in sorted(word_index.items(),key=lambda x:x[1]):
    if i > vocab_size:
        break
    if word in word2vec.wv.vocab:
        embedding_vector = word2vec.wv[word]
        embedding_matrix[i] = embedding_vector

In [0]:
embedding_matrix

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.16866052e+00, -7.70397484e-01,  5.36463439e-01, ...,
         4.05603141e-01,  1.03146255e+00,  5.40008426e-01],
       [ 1.81770131e-01, -3.19990814e-01, -1.54910731e+00, ...,
         5.80117047e-01,  1.93074954e+00,  2.35541433e-01],
       ...,
       [ 3.41043323e-01,  1.10295914e-01, -4.41503316e-01, ...,
        -3.05411249e-01,  8.40625614e-02, -1.12593189e-01],
       [ 3.31337422e-01,  2.60454744e-01, -2.44804904e-01, ...,
         7.71929562e-01, -4.43852991e-02, -1.11080392e-03],
       [ 3.35533053e-01,  2.15908974e-01,  3.63179684e-01, ...,
        -8.98603499e-02,  3.16696137e-01,  1.12234205e-01]])

In [0]:
# Making the Embedding layer false so it does not train again and we have less training time.
model_Embedding_Pretrained = Sequential()
model_Embedding_Pretrained.add(Embedding(vocab_size + 1,
                    embedding_vector_length,
                    input_length=maxlen,
                   weights=[embedding_matrix],
                   trainable=False)
         )
model_Embedding_Pretrained.add(LSTM(256, dropout = 0.2, recurrent_dropout= 0.2))
model_Embedding_Pretrained.add(Dense(1, activation= 'sigmoid'))

In [0]:
model_Embedding_Pretrained.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [0]:
# filepath="/gdrive/My Drive/NLP/Sequence Modelling/Weights/weights.best.hdf5"
# checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
ES = EarlyStopping(monitor='val_acc', min_delta=0, patience=0, mode='auto', baseline=None, restore_best_weights=False)
callbacks_list = [ES]

In [0]:
%%time
model_Embedding_Pretrained.fit(x_train,y_train,
          epochs=10,
          batch_size=128,          
          validation_data=(x_test, y_test),
         verbose=1, callbacks = callbacks_list)

Train on 25000 samples, validate on 25000 samples
Epoch 1/10
25000/25000 [==============================] - 128s 5ms/step - loss: 0.6436 - acc: 0.6226 - val_loss: 0.5765 - val_acc: 0.6934
Epoch 2/10
25000/25000 [==============================] - 125s 5ms/step - loss: 0.5745 - acc: 0.6972 - val_loss: 0.5281 - val_acc: 0.7366
Epoch 3/10
25000/25000 [==============================] - 125s 5ms/step - loss: 0.5271 - acc: 0.7322 - val_loss: 0.5206 - val_acc: 0.7500
Epoch 4/10
25000/25000 [==============================] - 123s 5ms/step - loss: 0.4887 - acc: 0.7594 - val_loss: 0.4884 - val_acc: 0.7839
Epoch 5/10
25000/25000 [==============================] - 122s 5ms/step - loss: 0.4484 - acc: 0.7888 - val_loss: 0.4293 - val_acc: 0.8044
Epoch 6/10
25000/25000 [==============================] - 120s 5ms/step - loss: 0.4229 - acc: 0.8041 - val_loss: 0.4103 - val_acc: 0.8115
Epoch 7/10
25000/25000 [==============================] - 120s 5ms/step - loss: 0.4101 - acc: 0.8093 - val_loss: 0.4272 - 

## Retrive the output of each layer in keras for a given single test sample from the trained model you built

In [0]:
# Predicting using model created by training on our own embeddings
model.predict_classes(x_test)

array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [1]], dtype=int32)

In [0]:
# Predicting using pretrained model
model_Embedding_Pretrained.predict_classes(x_test)

array([[0],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]], dtype=int32)

In [0]:
decoded_review = ' '.join([reverse_word_index.get(i, "") for i in x_test[2]])

In [0]:
decoded_review

"grade marc go and but be lot it oliver movie is and picture and feel this of ensue like different just clichéd girl at finds is and no and glory any is children's just moment like mixing any of and leaving for as it even cliche to purchased is money easily egypt and glory any is and i i liam film as and set actually easily like outdated sequel any of and ryan made film is and br and constant and of 90s letting deep in act made of road in of and movie and rural vhs of share in reaching fact of and polly spinal of 90s to them book are is unfamiliar mercy and mode they funniest is white courage and vegas wooden br of gender and unfortunately of 1968 no of years hokey and true up and and but 3 all ordinary be oblivious to and were deserve film clone and of creative br comes their kung who is assuming bias out new all it incomprehensible it episode much that's including i i cartoon of my certain no as rooting over you with way to cartoon of enough for that with way who is finished and they

In [0]:
print (model_Embedding_Pretrained.predict_classes(x_test[2:3]))
# print (model.predict_classes(decoded_review))

[[1]]
